// Generated by CoffeeScript 1.6.2
(function() {
  jQuery(function() {
    $.CV = function(el, options) {
      var state;

      state = "";
      this.settings = {};
      this.$el = $(el);
      this.setState = function(_state) {
        return state = _state;
      };
      this.getState = function() {
        return state;
      };
      this.getSetting = function(key) {
        return this.settings[key];
      };
      this.callSettingFunction = function(name, args) {
        if (args == null) {
          args = [];
        }
        return this.settings[name].apply(this, args);
      };
      this.init = function() {
        this.settings = $.extend({}, this.defaults, options);
        this.setState("ready");
        return this.$el.html(this.getSetting("key"));
      };
      this.init();
      return this;
    };
    $.CV.prototype.defaults = {
      key: "0AsxYR5Y3N6DjdHJWZDNNcjhmZ0ZSb2hFTjU0MDBjZ2c"
    };
    return $.fn.CV = function(options) {
      return this.each(function() {
        var plugin;

        if ($(this).data("CV") === void 0) {
          plugin = new $.CV(this, options);
          return $(this).data("CV", plugin);
        }
      });
    };
  });

}).call(this);
